name: lo5t-build
on:
  push:
    branches:
      - 'Lo5t'         # matches every branch
  pull_request:

env:
  COMPILER: clang

jobs:
  build:
    strategy:
      fail-fast: true
    runs-on: ubuntu-20.04
    if: github.repository == 'locus313/azerothcore-wotlk'
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          submodules: recursive
      - name: Apply core patch
        run: git apply modules/mod-solo-lfg/lfg-solo.patch
      - name: Cache
        uses: actions/cache@v2
        with:
          path: var/ccache
          key: ccache:ubuntu-20.04:${{ github.ref }}:${{ github.sha }}
          restore-keys: |
            ccache:ubuntu-20.04:${{ github.ref }}
            ccache:ubuntu-20.04
      - name: Configure OS
        run: source ./acore.sh install-deps
        env:
          CONTINUOUS_INTEGRATION: true
      - name: Create conf/config.sh
        run: source ./apps/ci/ci-conf.sh
      - name: Import db
        run: source ./apps/ci/ci-import-db.sh
      - name: Build
        run: source ./apps/ci/ci-compile.sh
      - name: Dry run
        run: source ./apps/ci/ci-worldserver-dry-run.sh
      - name: Check startup errors
        run: source ./apps/ci/ci-error-check.sh
      - name: Run unit tests
        run: source ./apps/ci/ci-run-unit-tests.sh
