on: push
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: repo-sync
      uses: wei/git-sync@v2
      with:
        source_repo: "https://github.com/azerothcore/azerothcore-wotlk.git"
        source_branch: "master"
        destination_repo: "https://$GH_USERNAME:$GH_TOKEN@github.com/locus313/azerothcore-wotlk.git"
        destination_branch: "master"
